### ISSUE TITLE
abort "RawBoost"

### ISSUE THREAD

**Issue by Doge-e7i** [ductuantruong/tcm_add#3]
Hello! I'm trying to reproduce your project. But i'm in trouble.
In the file "utils.py", line 5, code is "from RawBoost import  process_Rawboost_feature".But there is no flle named "RawBoost" in dir "tcm_add" and "fairseq_dir". And I tried to search keyword "RawBoost" in all project dir, but i got nothing. Are you miss upload "RawBoost"? Or maybe am i lostt some steps? Could you help me? Thx!

**Comment by ductuantruong** [comment]
Hi @DoubleTree-Doge,

My bad. I have just uploaded the RawBoost script. 

Thank you for your interest!
