### ISSUE TITLE
about run the "eval.py"

### ISSUE THREAD

**Issue by Doge-e7i** [ductuantruong/tcm_add#4]
Before your answer, I have already solve the "RawBoost.py" problem. But I still appreciate your reply. And not I am in another trouble.Sorry to be a bother again. 
I download the file "[ASVspoof 2021 LA database](https://zenodo.org/records/4837263)". And i tried to run "eval.py" by load your model "avg_5_best.pth". I successfully got a results. It like this:
```
LA_E_9332881 -4.7268171310424805
LA_E_6866159 -4.681441783905029
LA_E_5464494 -4.33859920501709
LA_E_4759417 -4.358471870422363
LA_E_2667748 -4.466348648071289
LA_E_8589971 -4.607029438018799
LA_E_1911364 -4.593714714050293
LA_E_5298786 -4.623228073120117
LA_E_2042719 -4.72429084777832
LA_E_5449181 -4.654930114746094
...more 181556 rows
```
Is it a right result? I can't sure that.
In your paper,  you evaluate a model by EER (%) and min t-DCF. How can i get them by my rusults?
And in the table 1 on your paper, you wrote that "ASVspoof 2021 eval set with fixed-length (Fix) and  variable-length(Var)". I don't know what is Fix and Var. And I can't find them in code. 
I just started working on ASV so I don't know much. I really need a help, thx!

**Comment by ductuantruong** [comment]
Hi, 

I have added the script and update the README about how to get the EER & min t-DCF. Furthermore, 'Fix' means fixed-duration input evaluation, 'Var' means variable-duration input evaluation. Since the 'Var' result is worse than the 'Fix', so I just put the 'Fix' code. You can compare to the Fix result only.

**Comment by Doge-e7i** [comment]
Hi,
I have got EER and min t-DCF by your way. I compared them with the data from your paper but I found some bad. Result EER by model "DF/fix/avg_5_best.pth" was same to your paper data. Then, I used your 5 pretrained models "LA/fix/best_x.pth" and I computed EER and min t-DCF of them. But I could't got the data on your paper. My results are worse.
There are results of EER and min t-DCF by "LA/fix/best_4.pth".

```
         C1     C2     C3     C4     C5     C6     C7   Pooled
 A07    0.00   0.55   1.56   0.46   0.60   2.76   1.43   1.13
 A08    0.00   0.66   2.21   0.51   0.60   3.36   1.53   1.47
 A09    0.00   0.58   2.03   0.46   0.61   3.15   1.36   1.29
 A10    0.24   0.95   4.89   0.76   0.90   5.18   2.25   3.62
 A11    0.24   0.76   4.66   0.76   0.75   4.51   2.21   3.25
 A12    0.15   0.76   2.51   0.73   0.75   3.57   1.84   2.29
 A13    0.00   0.67   2.16   0.52   0.60   3.90   1.58   1.51
 A14    0.00   0.67   2.98   0.52   0.60   3.56   1.53   1.60
 A15    0.06   0.68   2.57   0.73   0.68   3.45   1.66   1.82
 A16    0.15   0.67   1.98   0.73   0.67   3.32   1.64   1.67
 A17    0.88   1.40   3.70   1.28   1.36   6.06   2.16   2.92
 A18    2.09   2.80   6.31   2.11   2.87   7.82   3.35   4.88
 A19    0.97   1.47   4.52   1.19   1.41   6.41   2.46   3.34
Pooled  0.41   0.94   3.56   0.77   0.89   4.50   2.08   2.74
```
```
         C1     C2     C3     C4     C5     C6     C7   Pooled
 A07   0.0610 0.1596 0.2578 0.0755 0.1627 0.2554 0.0868 0.1762
 A08   0.0613 0.1768 0.2868 0.0777 0.1800 0.3015 0.0918 0.1933
 A09   0.2405 0.3536 0.4284 0.3054 0.3447 0.4701 0.3928 0.4183
 A10   0.0661 0.1693 0.3350 0.0847 0.1722 0.3129 0.1059 0.2361
 A11   0.0664 0.1603 0.3217 0.0814 0.1673 0.2976 0.1039 0.2220
 A12   0.0659 0.1701 0.2880 0.0798 0.1763 0.2934 0.1011 0.2117
 A13   0.0615 0.1825 0.3141 0.0783 0.1863 0.3130 0.0909 0.1980
 A14   0.0585 0.1584 0.2776 0.0731 0.1614 0.2764 0.0864 0.1768
 A15   0.0596 0.1579 0.2678 0.0774 0.1617 0.2731 0.0904 0.1852
 A16   0.0600 0.1579 0.2513 0.0781 0.1620 0.2688 0.0936 0.1814
 A17   0.6845 0.7680 0.8044 0.7955 0.7188 0.7835 0.9937 0.7583
 A18   0.2481 0.5059 0.6036 0.2679 0.5136 0.6653 0.3581 0.5660
 A19   0.1061 0.3615 0.4626 0.1304 0.3694 0.5813 0.1725 0.3904
Pooled 0.0866 0.2122 0.3534 0.1050 0.2168 0.3604 0.1334 0.2615
```
Did I get something wrong? Or is it that the model you uploaded is not correct?

**Comment by ductuantruong** [comment]
Hi, 

You should average the 5 checkpoints to get to the final checkpoint & use it for evaluation.
